---
title: "LF fishery in Mexican Caribbean"
author: "Luis Malpica"
date: "Apr, 2017"
output:
  pdf_document: default
  html_document:
    code_folding: hide
---
```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = FALSE)
#code_folding: hide
```

```{r Libraries & data, include=F, cache=FALSE, message=F}
rm(list = ls())

#load
#library(plyr)
#library(tidyr)
library(reshape2)
library(dplyr)
library(ggplot2)
library(zoo)

#A custom theme for ggplot####
theme_gg <- function(base_size = 11, base_family = "") {
  theme_light() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "grey10"),
      axis.text = element_text(colour = "grey20",size=8),
      axis.title = element_text(colour = "grey20",size=10),
      legend.title = element_text(colour = "grey20", size = rel(1.2)),
      panel.border = element_rect(fill = NA, colour = "grey70", size = 1),
      legend.key.size = unit(0.8, "lines"),
      legend.text = element_text(size = rel(1), colour = "grey20"),
      legend.key = element_rect(colour = NA)
    )
}
```

```{r Data manipulation, include=T}
#Read and manipulate data####
d_surveys <- read.table("data/LF_Cozumel.csv",sep=",", header=T)
not <- cbind("Cocales Bajito", "Las Brisas")
d_surveys <- dplyr::filter(d_surveys, ! Sitio %in% not)

d_surveys <- d_surveys %>%  filter(!grepl("...Nov...",Fecha))

d_surveys$TL[is.na(d_surveys$TL)] <- 0

d_sur_melt <- reshape2::melt(d_surveys, id.vars = c("Fecha","Profundidad","Lat","Long","Ubicacion",
                                                  "Sitio","Area","Transecto"),
                    variable.name = "LF", value.name = "TL",na.rm = T)

d_sur_melt$TL[d_sur_melt$TL>0] <- 1

d_absLF <- summarise(group_by(d_sur_melt,Fecha,Lat,Long,Ubicacion,Sitio,Transecto),
                             Abund = (sum(TL)))

d_densLF <- merge(summarise(group_by(d_absLF,Fecha,Lat,Long,Ubicacion,Sitio),
                             AveLFm2 = (mean(Abund))/0.012),
                  summarise(group_by(d_absLF,Fecha,Lat,Long,Ubicacion,Sitio),
                             SDLFm2 = (sd(Abund))/0.012))

d_densLF <- mutate(d_densLF, SELFm2 = SDLFm2/(sqrt(12)))

d_densLF$Fecha <- as.Date(d_densLF$Fecha, "%d-%b-%y")

```

```{r LF plots, include=T,cache=FALSE, message=F}
#LF in Cozumel
ggplot(data=d_densLF, aes(x=Fecha, y=AveLFm2)) +
    geom_line() + facet_wrap(c("Sitio")) +
    geom_point() +
    geom_pointrange((aes(ymin=AveLFm2-SELFm2, ymax=AveLFm2+SELFm2))) +
  theme_gg()

```
